name: CI

on:
  push:
    # Run on the main branch
    branches:
      - main
      - release/*
  # Also on PRs, just be careful not to publish anything
  pull_request:
  # Allow to be called from other workflows (like "release")
  workflow_call:
  # But don't trigger on tags, as they are covered by the "release.yaml" workflow

jobs:

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: webiny/action-conventional-commits@8bc41ff4e7d423d56fa4905f6ff79209a78776c7

      - name: Check formatting
        run: |
          cargo fmt --check

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2

  clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: linux-clippy-${{ hashFiles('**/Cargo.toml') }}

      - name: Clippy
        run: cargo clippy --all-targets --tests --bins --workspace --examples -- -D warnings

  check:

    strategy:
      matrix:

        rust:
          - "1.76" # MSRV

        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Rust ${{ matrix.rust }}
        run: |
          rustup install ${{ matrix.rust }}

      - name: Install dependencies
        run: ${{ matrix.install }}

      - name: Tree
        run: cargo +${{ matrix.rust }} tree --workspace ${{ matrix.args }}

      - name: Check
        run: cargo +${{ matrix.rust }} check --workspace ${{ matrix.args }}

      - name: Test
        run: cargo +${{ matrix.rust }} test --workspace ${{ matrix.args }} -- --nocapture
